### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarshZero** [hamngku/PaheinBypass#2]
![image](https://github.com/hamngku/PaheinBypass/assets/31729048/dcbee22e-e912-4dba-bffc-168712abaae2)

**Comment by hamngku** [comment]
Yap, ucan try new version 1.1.1 support pahe link page 🙂

![Example](https://github.com/hamngku/PaheinBypass/assets/142080978/73da5d24-8778-4ef0-8660-0855c258df4d)
